export const stores = [
	{
		id: "1",
		title: "Walmart",
		subtitle: "Delivery",
		image: "./stores/Walmart.png",
		link: "#",
	},
	{
		id: "2",
		title: "Sprouts Farmers Market",
		subtitle: "Delivery • Pickup 7.4mi",
		image: "./stores/Sprouts Farmers Market.png",
		link: "#",
	},
	{
		id: "3",
		title: "The Container Store",
		subtitle: "Delivery",
		image: "./stores/The Container Store.png",
		link: "#",
	},
	{
		id: "4",
		title: "FoodsCo Delivery Now",
		subtitle: "Delivery",
		image: "./stores/FoodsCo Delivery Now.png",
		link: "#",
	},
	{
		id: "5",
		title: "Grocery Outlet",
		subtitle: "Delivery",
		image: "./stores/Grocery Outlet.png",
		link: "#",
	},
	{
		id: "6",
		title: "7-Eleven",
		subtitle: "Delivery",
		image: "./stores/7-Eleven.png",
		link: "#",
	},
	{
		id: "7",
		title: "Dollar Tree",
		subtitle: "Delivery",
		image: "./stores/Dollar Tree.png",
		link: "#",
	},
	{
		id: "8",
		title: "Costco",
		subtitle: "Delivery",
		image: "./stores/Costco.png",
		link: "#",
	},
	{
		id: "9",
		title: "Safeway",
		subtitle: "Delivery",
		image: "./stores/Safeway.png",
		link: "#",
	},
	{
		id: "10",
		title: "Target",
		subtitle: "Delivery",
		image: "./stores/Target.png",
		link: "#",
	},
	{
		id: "11",
		title: "Sephora",
		subtitle: "Delivery",
		image: "./stores/Sephora.png",
		link: "#",
	},
	{
		id: "12",
		title: "Best Buy",
		subtitle: "Delivery",
		image: "./stores/Best Buy.png",
		link: "#",
	},
	{
		id: "13",
		title: "The Wine Shop",
		subtitle: "Delivery",
		image: "./stores/The Wine Shop.png",
		link: "#",
	},
	{
		id: "14",
		title: "CVS Pharmacy®",
		subtitle: "Delivery",
		image: "./stores/CVS Pharmacy.png",
		link: "#",
	},
	{
		id: "15",
		title: "Mollie Stone's Markets",
		subtitle: "Delivery",
		image: "./stores/Mollie Stone's Markets.jpg",
		link: "#",
	},
	{
		id: "16",
		title: "Gus's Community Market",
		subtitle: "Delivery",
		image: "./stores/Gus's Community Market.png",
		link: "#",
	},
	{
		id: "17",
		title: "Manila Oriental Market",
		subtitle: "Delivery",
		image: "./stores/Manila Oriental Market.png",
		link: "#",
	},
	{
		id: "18",
		title: "Bed Bath & Beyond",
		subtitle: "Delivery",
		image: "./stores/Bed Bath & Beyond.png",
		link: "#",
	},
	{
		id: "19",
		title: "Rainbow Grocery",
		subtitle: "Delivery",
		image: "./stores/Rainbow Grocery.png",
		link: "#",
	},
	{
		id: "20",
		title: "FoodsCo",
		subtitle: "Delivery",
		image: "./stores/FoodsCo Delivery Now.png",
		link: "#",
	},
	{
		id: "21",
		title: "Restaurant Depot",
		subtitle: "Delivery",
		image: "./stores/Restaurant Depot.png",
		link: "#",
	},
	{
		id: "22",
		title: "Petco",
		subtitle: "Delivery",
		image: "./stores/Petco.jpg",
		link: "#",
	},
	{
		id: "23",
		title: "HMart",
		subtitle: "Delivery",
		image: "./stores/HMart.png",
		link: "#",
	},
	{
		id: "24",
		title: "BevMo!",
		subtitle: "Delivery",
		image: "./stores/BevMo!.png",
		link: "#",
	},
	{
		id: "25",
		title: "Smart & Final",
		subtitle: "Delivery",
		image: "./stores/Smart & Final.png",
		link: "#",
	},
	{
		id: "26",
		title: "Lucky Supermarkets",
		subtitle: "Delivery • Pickup 9.2mi",
		image: "./stores/Lucky Supermarkets.png",
		link: "#",
	},
	{
		id: "27",
		title: "Total Wine & More",
		subtitle: "Delivery",
		image: "./stores/Total Wine & More.png",
		link: "#",
	},
	{
		id: "28",
		title: "Sports Basement",
		subtitle: "Delivery",
		image: "./stores/Sports Basement.png",
		link: "#",
	},
	{
		id: "29",
		title: "Indian Market and Liquor",
		subtitle: "Delivery",
		image: "./stores/Indian Market and Liquor.png",
		link: "#",
	},
	{
		id: "30",
		title: "Andronico's Community Markets",
		subtitle: "Delivery",
		image: "./stores/Andronico's Community Markets.png",
		link: "#",
	},
	{
		id: "31",
		title: "ButcherBox",
		subtitle: "Delivery",
		image: "./stores/ButcherBox.png",
		link: "#",
	},
	{
		id: "32",
		title: "La Fromagerie Cheese Shop",
		subtitle: "Delivery",
		image: "./stores/La Fromagerie Cheese Shop.png",
		link: "#",
	},
	{
		id: "33",
		title: "Healthy Spot - Organic Pet Food & Supply",
		subtitle: "Delivery",
		image: "./stores/Healthy Spot Organic Pet Food & Supply.jpg",
		link: "#",
	},
	{
		id: "34",
		title: "Lunardi's Markets",
		subtitle: "Delivery",
		image: "./stores/Lunardi's Markets.png",
		link: "#",
	},
	{
		id: "35",
		title: "Walgreens",
		subtitle: "Delivery",
		image: "./stores/Walgreens.png",
		link: "#",
	},
	{
		id: "36",
		title: "Staples",
		subtitle: "Delivery",
		image: "./stores/Staples.png",
		link: "#",
	},
	{
		id: "37",
		title: "Cardenas Markets",
		subtitle: "Pickup 41.8mi",
		image: "./stores/Cardenas Markets.png",
		link: "#",
	},
	{
		id: "38",
		title: "Bi-Rite Market",
		subtitle: "Delivery • Pickup 2.6mi",
		image: "./stores/Bi-Rite Market.jpg",
		link: "#",
	},
	{
		id: "39",
		title: "Big Lots",
		subtitle: "Delivery",
		image: "./stores/Big Lots.png",
		link: "#",
	},
	{
		id: "40",
		title: "Woodlands",
		subtitle: "Delivery",
		image: "./stores/Woodlands.png",
		link: "#",
	},
	{
		id: "41",
		title: "New Leaf Community Markets",
		subtitle: "Pickup 22.3mi",
		image: "./stores/New Leaf Community Markets.png",
		link: "#",
	},
	{
		id: "42",
		title: "CHEF'STORE",
		subtitle: "Delivery Pickup 22.6mi",
		image: "./stores/CHEF'STORE.png",
		link: "#",
	},
	{
		id: "43",
		title: "O Organics Market",
		subtitle: "Delivery",
		image: "./stores/O Organics Market.png",
		link: "#",
	},
	{
		id: "44",
		title: "FoodMaxx",
		subtitle: "Pickup 28.2mi",
		image: "./stores/FoodMaxx.png",
		link: "#",
	},
	{
		id: "45",
		title: "Falletti Foods",
		subtitle: "Delivery",
		image: "./stores/Falletti Foods.png",
		link: "#",
	},
	{
		id: "46",
		title: "Mi Tierra Market",
		subtitle: "Delivery",
		image: "./stores/Mi Tierra Market.png",
		link: "#",
	},
	{
		id: "47",
		title: "LeBeau Nob Hill",
		subtitle: "Delivery",
		image: "./stores/LeBeau Nob Hill.png",
		link: "#",
	},
	{
		id: "48",
		title: "The Vitamin Shoppe®",
		subtitle: "Delivery",
		image: "./stores/The Vitamin Shoppe.jpg",
		link: "#",
	},
	{
		id: "49",
		title: "The Epicurean Trader",
		subtitle: "Delivery",
		image: "./stores/The Epicurean Trader.png",
		link: "#",
	},
	{
		id: "50",
		title: "Wine Meats Cheese",
		subtitle: "Delivery",
		image: "./stores/Wine Meats Cheese.png",
		link: "#",
	},
	{
		id: "51",
		title: "Mission Grocery & Liquor",
		subtitle: "Delivery",
		image: "./stores/Mission Grocery & Liquor.jpg",
		link: "#",
	},
	{
		id: "52",
		title: "Gene's Fine Foods",
		subtitle: "Pickup 28.4mi",
		image: "./stores/Gene's Fine Foods.png",
		link: "#",
	},
	{
		id: "53",
		title: "Glen Ellen Village Market",
		subtitle: "Pickup 40.2mi",
		image: "./stores/Glen Ellen Village Market.png",
		link: "#",
	},
	{
		id: "54",
		title: "Sunbasket",
		subtitle: "Delivery",
		image: "./stores/Sunbasket.jpeg",
		link: "#",
	},
];

export const cards = [
	{
		id: "1",
		title: "Choose what you want",
		subtitle:
			"Select items from your favorite grocery stores at Instacart.com or in the app.",
		image: "./images/How it works.jpg",
	},
	{
		id: "2",
		title: "See real-time updates",
		subtitle:
			"Personal shoppers pick items with care. Chat as they shop and manage your order.",
		image: "./images/Real time updates.jpg",
	},
	{
		id: "3",
		title: "Get your items same-day",
		subtitle:
			"Pick a convenient time for you. Enjoy Instacart's 100% quality guarantee on every order.",
		image: "./images/Same day delivery.jpg",
	},
];

export const stats = [
	{
		id: "1",
		title: "500 million products",
		subtitle: "available to shop across the catalog",
	},
	{
		id: "2",
		title: "40,000 stores",
		subtitle: "from local grocers to chain stores",
	},
	{
		id: "3",
		title: "5,500+ cities",
		subtitle: "served across the U.S. & Canada",
	},
	{
		id: "4",
		title: "Millions of orders",
		subtitle: "delivered or picked up yearly",
	},
];

export const questions = [
	{
		id: "1",
		title: "How does Instacart delivery and curbside pickup work?",
		subtitle: `Instacart makes it easy to order from your favorite stores. Shop for items from stores near you, with a selection of more than 500 retailers and trusted local grocers across North America. Then, Instacart will connect you with a personal shopper in your area to shop and deliver your order. Contactless delivery is available with our “Leave at my door” option.<br><br>You can track your order’s progress and communicate with your shopper every step of the way using the Instacart app or website.<br><br>Instacart also offers curbside pickup at select retail locations. Simply place your order and choose a pickup time, and a shopper will prepare your order at the store.<br><br>When you get to the store, use the Instacart app to notify us. Depending on the store, a shopper or store employee will bring the groceries to your car, or you can pick them up at the designated area.<br>`,
	},
	{
		id: "2",
		title: "How much does Instacart cost?",
		subtitle: `You don’t need a membership to order with Instacart. In fact, you can even order from warehouse clubs, like Costco, Sam’s Club, and BJ’s Wholesale Club, without a retailer club membership.<br><br>To get started, create an account, select the store you want to shop, and place your order. New customers may be eligible for free delivery promotions.<br><br>Delivery: Fees start at $3.99 for same-day orders over $35. Fees vary for one-hour deliveries, club store deliveries, and deliveries under $35.<br><br>Pickup: There may be a “pickup fee” (equivalent to a delivery fee for pickup orders) on your pick up order.<br><br>Service fees: Service fees vary and are subject to change based on factors like location and the number and types of items in your cart. Orders containing alcohol have a separate service fee.<br><br>With an optional Instacart Express membership, you can get $0 delivery fee on every order over $35 and lower service fees too.<br><br>Tipping is optional but encouraged for delivery orders. It’s a great way to show your shopper appreciation and recognition for excellent service. 100% of your tip goes directly to the shopper who delivers your order.<br>`,
	},
	{
		id: "3",
		title: "Will I pay the same price on Instacart as I would in the store?",
		subtitle: `Retail partners set the prices of items on the Instacart marketplace. While many retailers offer everyday store prices on Instacart, some retailers may set prices on the Instacart platform that are different from in-store prices.<br><br>You can view pricing policies for each retailer on the Instacart app and website.<br>`,
	},
	{
		id: "4",
		title:
			"What happens if something is out of stock and need to give specific instructions?",
		subtitle: `Instacart makes it easy to communicate with your shopper. When an item you want is out-of-stock at the store, your shopper will follow your replacement preferences.<br><br>You can set item and delivery instructions in advance, as well as chat directly with your shopper while they shop and deliver your items. You can tell the shopper to:<br><br>- Find Best Match: By default, your shopper will use their best judgement to pick a replacement for your item.<br>- Pick Specific Replacement: You can pick a specific alternative for the shopper to purchase if your first choice is out-of-stock.<br>- Don’t Replace: For items you’d rather not replace, choose “Don’t replace” to get a refund if the item is out of stock.<br><br>You can update or cancel your order as long as your shopper hasn’t started shopping. If you need to make changes after shopping has started, you can use the app or website to approve replacements or chat with your shopper.<br>`,
	},
	{
		id: "5",
		title: "What happens if there's an issue with my order?",
		subtitle: `If something isn’t right, you’ve got options. In the Instacart app or website, you can report:<br><br>- Missing items<br>- Incorrect items<br>- Damaged items<br>- Poor replacements<br>- Early/late orders<br><br>If an order never came, or you get someone else’s order, you can reach out to Instacart Care.<br>`,
	},
	{
		id: "6",
		title: "Can I get contactless delivery with Instacart?",
		subtitle: `The health and safety of our community is our number one priority. We are excited to offer contactless delivery through our Leave at My Door delivery feature.<br><br>Leave at My Door delivery gives you the flexibility to have your groceries delivered without having to come to the door or be at home. You can leave delivery instructions for your shopper at checkout, and we’ll notify you when your order arrives.<br><br>Leave at My Door is now the default setting for all Instacart deliveries. If you’d prefer to not use this feature, simply uncheck the box that says “Leave at my door if I’m not around” at checkout.<br><br>Customers who order alcohol, prescriptions, or certain high-value items may need to show ID upon delivery. We ask shoppers to wear masks whenever they come into contact with customers.<br>`,
	},
];
